# Site settings
title:          Tale
description:    "Minimal Jekyll theme for storytellers"
url:            https://altera520.github.io/

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Permalinks
permalink:      /:year-:month-:day/:title

#setup
title:        Juneee Blog
url:          https://altera520.github.io/
baseurl:      ""

# About
author:
  name:         Gyojun An
  url:          https://altera520.github.io/
  email:        sencom1028@gmail.com  
  github:       Altera520

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Excludes
exclude: [ Gemfile, Gemfile.lock ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale

collections:
  algorithm:
    output: true
    sort_by: date
    permalink: /blog/:name
  db:
    output: true
    sort_by: date
  etc:
    output: true
    sort_by: date
  network:
    output: true
    sort_by: date
  os:
    output: true
    sort_by: date
  programming:
    output: true
    sort_by: date
collections_dir: source